on:
  pull_request:
    types: [opened]
    paths:
    - '**.sql'

jobs:
  add-sql-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: ".github/auto_assign_sql.yml"
